title: SpaceSheep Schools
email: support@sheep16.org
description: >-
  בתקופה מאתגרת וחסרת ודאות, נדרשים כלי לימוד חדשניים וגמישים המאפשרים לימוד
  מרחוק ובהתאמות הנדרשות ללימוד כזה, אך גם גמישות ללימוד בכיתה באופן יותר
  מסורתי, וכמובן שילוב בינהם. זו בדיוק תפיסת עולמנו.
baseurl: ""
url: "https://schools.spacesheep.dev"
twitter_username: bysheep16
github_username:  sheepsixteen

permalink: none

markdown: SheepProcessor

kramdown:
  parse_block_html: true

theme: 
plugins:
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-turbolinks

